### ISSUE TITLE
Documentation needs update

### ISSUE THREAD

**Issue by philicious** [chef-cookbooks/chef-client#281]
with https://github.com/opscode-cookbooks/chef-client/commit/7b1e1266a5e6f38bd9b040ee473e43b11f715a40#diff-25e5d4a4446ae12a0d6f1162b6160375 you introduced `'verify_api_cert' => true`
However https://docs.chef.io/server_security.html lists it as default false.

**Comment by juliandunn** [comment]
Yeah, there's an interlink between `ssl_verify_mode` and `verify_api_cert` that should be mentioned in the docs on docs.chef.io @jamescott 

Because this cookbook is intended to work on Chef 11 as well, where we don't do SSL verification by default, `verify_api_cert` is the lowest common denominator to ensure that at least the SSL communication with the Chef server is verified.

**Comment by jtimberman** [comment]
I think we should do here what we did with chef-server and make a cut away from 11 in a branch and release 12+ only from master with a new major version bump. Along that line said major version should be a refactoring to make all these recipes into resources with providers per platform a la @someara 's work on httpd and mysql. I'll open an issue detailing my ideas on this later today.

**Comment by tas50** [comment]
This docs page has been updated since this bug was filed. Any other issues with the docs should go to the docs repo so the docs team can fix them:

https://github.com/chef/chef-web-docs
