### ISSUE TITLE
Syntax changed for Ohai disabled_plugins

### ISSUE THREAD

**Issue by jfbibeau** [chef-cookbooks/chef-client#346]
In the current version of chef-client cookbook, the config.rb file generated results in the following warning (chef client 12.5.1):

[2015-10-22T15:03:46-04:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration file to configure :disabled_plugins for ohai.

Would it make sense to update this cookbook to render instead, from:

`Ohai::Config[:disabled_plugins] = [:Passwd]`

to

`ohai.disabled_plugins = [:Passwd]`

I can make a PR if needed, just need the go-ahead.

**Comment by lamont-granquist** [comment]
It would make sense to do that but only if the ohai version supports the new syntax.

**Comment by jfbibeau** [comment]
@lamont-granquist The new syntax works in Chef 12.5.1 with Ohai 8.7.0. Anything else we need to make sure of? I can submit a PR with the change if you'd like. Getting tired of seeing that deprecation warning on all my clients :)

**Comment by lamont-granquist** [comment]
Just use this kind of code to check against Ohai::VERSION rather than rolling your own version check:

http://stackoverflow.com/questions/19516077/how-do-i-check-if-chefs-version-mets-a-gem-requirement-from-inside-a-recipe

You probably want to do the check in the recipe code and then inject a boolean into the template rather than dumping all that code directly into the template, although in this case its a bit 'meh' on if that produces better looking code or not...  Kind of up to you, if jamming all the logic into the template doesn't look too awful that would be simpler...

**Comment by jfbibeau** [comment]
Neato. I'll take a look and report back.

**Comment by jfbibeau** [comment]
Do we need an ohai version check if all ohai versions bundled with chef 11.6.0+ support the new syntax?

**Comment by lamont-granquist** [comment]
Yeah, theoretically someone could install ohai and chef differently outside of the omnibus packages.  The pin should be against ohai and not chef, and we still need to support old ohai/chef in this cookbook.

**Comment by jfbibeau** [comment]
Ok, I saw on the readme "Chef Client 11.6.0 or higher" as a requirement so thought that would make our lives easier.

**Comment by lamont-granquist** [comment]
oh, heh, the new syntax is only supported in >=12.5.1, i didn't read "11.6.0+" closely enough...
