### ISSUE TITLE
Restarting systemd-journald causes chef-client.service to fail (STDOUT) or all future runs to fail (logfile)

### ISSUE THREAD

**Issue by mathewcrane** [chef-cookbooks/chef-client#359]
Restarting systemd-journald causes chef-client.service to fail (STDOUT) or all future runs to fail (logfile).

Tested on chef client 12.0.3 and 12.6.0, using the standard systemd service configuration on EL7.1+.

to reproduce using STDOUT:
```
client.rb: log_location STDOUT
systemctl restart chef-client.service
systemctl restart systemd-journald
killall -USR1 chef-client
chef-client will die
```

to reproduce using /var/log/chef/client.log
```
client.rb: log_location "/var/log/chef/client.log"
systemctl restart chef-client.service
systemctl restart systemd-journald
killall -USR1 chef-client
```

all future runs fail with the following error:
```
[2016-02-10T20:29:48+00:00] ERROR: Running exception handlers
[2016-02-10T20:29:48+00:00] ERROR: Exception handlers complete
[2016-02-10T20:29:48+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-02-10T20:29:48+00:00] ERROR: Broken pipe @ io_write - <STDOUT>
[2016-02-10T20:29:48+00:00] ERROR: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

restarting chef-client.service resolves the issue, but this is less than ideal (nodes stop converging!)

I can work around this by chaining a notifies to the systemd-journald service resource, but it seems hacky and my suspicion is that other systemd service restarts may trigger this condition as well.

Is this a known issue? Please let me know if you need any further information.

**Comment by nathwill** [comment]
maybe related? https://bugs.freedesktop.org/show_bug.cgi?id=84923

**Comment by tas50** [comment]
@mathewcrane Can you confirm if this is still an issue on a fully updated RHEL system with the latest chef-client?

**Comment by mathewcrane** [comment]
@tas50 I've developed a workaround for this by updating the chef-client.service systemd unit file to restart on failure. I won't have a chance to test latest chef-client or RHEL7.2 for a few weeks at least, unfortunately.

**Comment by tas50** [comment]
the restart on failure behavior is now our default. I'm going to close this out, but feel free to open it up if this is still an issue.

https://github.com/chef-cookbooks/chef-client/pull/396

**Comment by mathewcrane** [comment]
Thanks for the follow-up, good to know.

**Comment by kamaradclimber** [comment]
We've been hit by this bug as well.

The restart-on-failure avoids manual intervention but looses all notifications.

**Comment by petracvv** [comment]
@tas50 It appears that this is still happening. I was able to reproduce this on CentOS 7.3.1611 with chef-client 12.21.1 and chef-client 13.4.19 (both running as a daemon) using the instructions provided by @mathewcrane. 

We are running the client with the default `client_fork true` setting (as set by the chef-client cookbook) and I believe that may be why this is still happening even with the `Restart = always` in the service file. Systemd does not keep track of the status of any failed children of the daemon it is monitoring so that Restart is never triggered as the parent chef-client daemon never exits or errors out.

See: https://unix.stackexchange.com/questions/312491/how-does-systemd-handle-the-death-of-a-child-of-a-managed-process

**Comment by bnwoods** [comment]
This appears to be an issue again in 14.11.21. We had the problem while on Chef 12 -- the issue went away with the Chef 13.x.x version we were on, and now it's back.

**Comment by grdz** [comment]
I still got this exact issue on chef-client 15.5.17, on Centos 7. I think that this should be open.
