### ISSUE TITLE
Attribute node['chef_client']['cache_path'] doesn't works precisely 

### ISSUE THREAD

**Issue by tiagobevilaqua** [chef-cookbooks/chef-client#384]
When I set the `default['chef_client']['cache_path']` to a different location of `/var/chef/cache`, for example, `/home/opscode/cache`, the entry inside `client.rb` is not created.

So, the cache folder it continues been in /var/chef/cache until I put manually the cache_path inside the client.rb, or edit the template client.rb.erb to build this file with this parameter.

`cache_path "/home/opscode/cache"`

But, beside this, the the daemonized process create another directory called 'cache' inside the value passed by cache_path, in other words, the `/home/opscode/cache/cache` it is created to be used as cache folder.

Am I doing something wrong?
### Versions Info

```
# chef-client --version
Chef: 12.8.1
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)
# grep -i version cookbooks/chef-client/metadata.rb
version           '4.3.3'
# rpm -qa chef\*
chef-server-core-12.4.1-1.el6.x86_64
```

**Comment by Vanders** [comment]
I've run into a similar problem: my wrapper cookbook `attributes/default.rb` contains:
```
default['chef_client']['backup_path'] = '/var/lib/chef'
default['chef_client']['cache_path'] = '/var/cache/chef'
```
but neither file_backup_path or file_cache_path are rendered into client.rb

**Comment by lamont-granquist** [comment]
unless i'm wrong this was broken over 6 years ago with:

https://github.com/chef-cookbooks/chef-client/commit/17fa8989d9a83658c7fd6622a437b454fe97d397

and the documentation and the attributes should probably be updated to use `default['chef_client']['config']['file_cache_path']` instead of the `cache_path`, etc.  i'm unclear what any of the attributes are doing that are setting the old config values.
