### ISSUE TITLE
Add "on boot" option for applicable recipes

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/chef-client#409]
### Suggestion:

I'd like chef-client to run immediately on booting.

In cron, this can be done with `@reboot` and Windows tasks have a similar trigger.

Obviously, services wouldn't need or want this.

The use cases:
- Some recipes have to reboot after running.  This lets Chef pick up where it left off after the reboot (linux kernel changes, some windows things).
- If a system is down for a while it should run Chef ASAP to get compliant again.

**Comment by thomasrutkowski** [comment]
This makes several of us. 
I've been searching for a way to do just this and am currently looking at having cron kick of a converge just after reboot. 
Are there any strong contraindications to force a converge via cron? Perhaps I haven't looked in the right places, but there's seems to be very little information on the subject.

**Comment by docwhat** [comment]
Nope. Works great. 

I use it for all our Linux boxes.

**Comment by willdearborn** [comment]
I thought I saw a notification about a new option to run a converge on daemon startup, but I'm not finding it.  I would also like this option, if it doesn't exist.

**Comment by Stromweld** [comment]
For windows with the new recommended task instead of service the windows_task provider should be enhanced to allow :onstart with recurring options so the default chef-client task can be setup to run right away on boot as well as every 30 minutes etc... 

Currently I have chef-client setup with defaults and have a recipe creating a second task to accomplish the initial run on boot. Unfortunately the frequency when changed from :minute to :onstart doesn't set the recurring options in windows task scheduler.

windows_task 'chef-client_onstartup' do
  command 'cmd.exe /c c:/opscode/chef/embedded/bin/chef-client.bat'
  cwd 'C:'
  user 'SYSTEM'
  run_level :highest
  frequency :onstart
  action [:create, :enable]
end

**Comment by dheerajd-msys** [comment]
Closing this issue based on https://github.com/chef-cookbooks/chef-client/pull/590#issuecomment-425682125 and https://github.com/chef-cookbooks/chef-client/pull/590#issuecomment-425708499.
