### ISSUE TITLE
Add the windows task name attribute

### ISSUE THREAD

**Issue by lbn-chef-team** [chef-cookbooks/chef-client#432]
Hello,

Can you add an attribute for windows scheduled task name in your next release?
Actually it is a constant "chef-client" resource name. 
In some production case, we have to do with two configuration of chef and then two task concurrently.

Best Regards,

**Comment by shoekstra** [comment]
Hi,

Having this as an attribute wouldn't help as you can't apply the same recipe twice with different attribute values, one of the values will override the other.

The best thing to do is include this cookbook in a wrapper cookbook and make use of the `chef_client_scheduled_task` resource directly in your own recipe where you can give each instance of it a unique name.

Hope that helps!

**Comment by tas50** [comment]
This cookbook ships with a resource now for setting up the scheduled task. It defaults to just 'Chef Client'. Making that an attribute could be sort of problematic since changing it would result in 2 different tasks. Since it is a resource though you can just use that resource directly in your own cookbook and skip the task recipe entirely. That would allow you to call it whatever you want.
