### ISSUE TITLE
Windows Task: Frequency cannot be updated after task creation.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [chef-cookbooks/chef-client#513]
### Cookbook version
8.1.7

### Chef-client version
12.19.36

### Platform Details
Windows 2012R2 Standard

### Scenario:
Once the windows task is created, I'm trying to update the frequency by which the task runs.  For example, the default frequency is 30 minutes.  If you execute the cookbook a task will be configured with the default 30 minutes.  However if you make a change to the frequency _after_ the task has already been created, the new frequency interval is not being respected, and the task remains at the frequency interval originally set when the task is created.  If the task is deleted on the host, then the task will be created with the correct frequency value, so this appears to be an issue with the 'test' harness of the cookbook not validating the frequency setting when the task already exists.

### Steps to Reproduce:

- Download the chef-client cookbook and leave default values.
- Create a wrapper cookbook that consumes the chef-client cookbook.
- Create an attributes folder in the wrapper cookbook with a default.rb file.  Inside the default.rb, add an entry for the 'frequency' attribute and leave it at the default of 1800.
- Upload the cookbook to the Chef Server.
- Add the cookbook to the run list of a test node.
- Execute the chef-client run on the managed node and confirm that the task is created with the default values.
- Update the chef-client wrapper cookbook and configure the 'frequency' attribute from 1800 to 2700 (45 minutes) and upload it to the Chef Server.
- Execute the chef-client on the managed node to converge on the latest cookbook version.  You'll observe that the frequency of the chef-client task, although updated to 45 minutes in the cookbook, is still configured to 30 minutes on the managed node.

### Expected Result:
After the task is initially created, the expectation is that any changes made to the frequency of the task, via the cookbook, will be set to the new value as defined therein.

### Actual Result:
The Windows task remains at the same frequency value that was provided when the task was initially created, but does not change if the frequency value is updated to a different value on subsequent chef-client converges.  The only way you can get the task to realize the new value is to delete the task and have the chef-client process recreate it.

**Comment by tas50** [comment]
This is a limitation of the scheduled task resource in the windows cookbook. Chef 13 shipped with a more robust resource built into chef-client and the upcoming Chef 13.3 release includes a lot of improvements to how this handles updates. There's a few different issues tracking this problem in the windows cookbook, but the real solution is going to be to upgrade to Chef 13.3 when it comes out so you can the legacy resource altogether.

**Comment by MichaelStankiewicz** [comment]
@tas50 Thanks for the reply and info.  So with the 13.3 client, will the chef-client cookbook still be in play?  If so, will the windows resource be replaced and embedded into the client binaries, or is there some other method altogether that will be used to configure the windows task?  I'm just curious as to how one would configure the windows task with the new solution you mention in version 13.3.

**Comment by tas50** [comment]
With Chef 13.3 we're still using the chef-client cookbook. What we did with Chef 13.0 was pull the windows_task resource into chef itself so users didn't need to rely on the windows cookbook to perform basic Windows automation. In bringing that resource into Chef it became apparent that there were some pretty significant shortcomings, one of which results in the problem you're seeing above. In each release of Chef since 13.0 we've worked to improve the windows_task resource to be fully idempotent. The 13.3 release that shipped on the 16th fixed an issue where the resource would not update unless the actual command changed. I'm fairly certain that's resulting in the bug you're running into. It's fixed here https://github.com/chef/chef/commit/52c6c1391c4d9d32038811ae49e07491ee3e235b

We have one more major change that I believe impacts your workflow that should make it into the upcoming 13.4 release: https://github.com/chef/chef/pull/6312

Please do let me know if this issue still happens for you with Chef 13.3. If so we obviously have some more work ahead of ourselves to get this resource fully idempotent.

**Comment by MichaelStankiewicz** [comment]
@tas50 So, I'm running Chef client 13.4 right now on a couple of my nodes, and every time a client converge occurs, it is indicating that 2 resources are always updated.  When I peer deeper into the converge activities, I see that it is my chef-client windows task configuration that keeps updating.  

Below is the output:
```
Recipe: chef-client::task
  * windows_service[chef-client] action configure_startup (skipped due to only_if)
  * chef_client_scheduled_task[Chef Client] action add
    * windows_task[chef-client] action create
```
It appears that the test harness for the task is not working properly, and instead, is treating each run as a new 'create' action rather than first validating if the task exists and _then_ making necessary changes.

Interestingly, this does not occur on my 12.19.36 version nodes with the same exact run lists.  So this does appear to be a bug in the new implementation you referred to above in client 13.
