### ISSUE TITLE
Cleanup existing runit services

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/chef-client#521]
We no longer support Runit, but we need to give people a path forward. We should properly migrate from runit to the new init systems. We're currently doing this in the push-jobs cookbook.

**Comment by rmiesen** [comment]
So what sort of workflow would be ideal here? If a system is a *NIX, it by definition must have _a_ variant of `init`, so just brute-forcing an install of an init package probably wouldn't be the desired outcome.

**Comment by tas50** [comment]
In the past we had done an install of runit as we saw that as the preferred init system. A lot of people disliked the shoehorning of runit into an existing Linux system that already has a working init system. We're moving away from the usage of runit in our community cookbooks as this point and instead relying on the out of the box setup of the individual distro. For most users on current distros that will be systemd, which provides a much better experience than runit.

**Comment by tas50** [comment]
I'm going to close this one out since we've brain stormed and realized that no matter how we handle this it won't work for all users. How users migrate init systems is going to be up to their particular environment.

**Comment by joegoggins** [comment]
I upgraded the `chef-client` cookbook from the runit based system to the non runit based system by simply adding a "delete the runit config" block by my cookbook.

While this seemed to work in my initial development, it had an undetected side effect of breaking all other runit supervised services on the system. **I now have many many servers with upgraded chef-client but all other runit stuff is broken**, where `service my-service status` returns:

```
$ service my-service status
chef-client (pid  21949) is running...
```

instead of 

```
service my-service status
run: my-service: (pid 29297) 872924s; run: log: (pid 24319) 873068s
```


This is the cookbook code I'm using to disable the runit one and enable the new one:

```
directory '/etc/service/chef-client' do
  action :delete
  recursive true
end

include_recipe('chef-client::config')
include_recipe('chef-client::init_service')
```

I know I'm on my own here, but I'd love any recommendations you can provide to put things back into a working order.
