### ISSUE TITLE
logrotate dependency breaks on Chef server 14 installations

### ISSUE THREAD

**Issue by alexkokkinos** [chef-cookbooks/chef-client#734]
chef-client attempts to install logrotate 3.0.2, which does not work on Chef 14:

```
Cookbook 'logrotate' version '3.0.2' depends on chef version [">= 15.3"], but the running chef version is 14.11.21
```

Perhaps chef-client should not use `>=` in `metadata.rb`? If i'm including `chef-client` in a policy I'm not sure what's the best method to control this kind of versioning issue. Is there any way to pin this without modifying my dozens of Policyfiles? 

Does Chef itself have any method of telling `chef install` to check dependencies against a specific Chef version? Right now, my policy build pipelines are completely blind to the version of Chef Server that's running, but I wonder if that's just me misusing Chef.

**Comment by tas50** [comment]
We very intentionally don't set upper limits on the cookbook dependencies. Historically we did and it led to massive problems when pins conflicted between differing cookbooks. You end up in situation where you can't depsolve or upgrade Chef Infra Client because there's no possible solution between cookbooks and client compatibility. Chef Infra Client 14 is end of life and has been for a bit over a year at this point. If you want to continue to run that version you'll need to pin your dependencies very carefully. A large portion of the community cookbook base is moving to requiring 15.3 or later. As time goes on you're going to run into more and more of this by using an EOL release.

**Comment by alexkokkinos** [comment]
Thanks @tas50 for giving me that greater context, especially since I'm a bit embarrassingly out of the loop on a lot of Chef topics. It's easy to suddenly be years into EOL status when you set something up and then leave it sitting around!
